#ifndef CARD_DEFINE_H
#define CARD_DEFINE_H
#include <map>
#include "GameDefine.h"
using namespace std;

typedef unsigned char uval;
typedef unsigned int  uint;
typedef unsigned char uchar;
typedef unsigned int UID;

#define MAKE_CARD(TYPE,VALUE)	(((TYPE)<<4) + (VALUE))
#define CARD_NULL	0

//中奖区域类型
enum emWinAreaType
{
	Area_Invalid = 0,	//无效值
	Area_Long = 1,		//龙
	Area_Hu = 2,		//虎
	Area_He = 3,		//和
};

//扑克牌花色
enum emCardColor
{
	TYPE_DIAMOND  = 0,//方块
	TYPE_CLUB	  = 1,//梅花
	TYPE_HEART	  = 2,//红桃
	TYPE_SPADE	  = 3,//黑桃
	TYPE_JOKER    = 4,//鬼
};

//扑克牌数值
enum emCardVal
{
	VAL_E  = 0,
	VAL_2	= 1,
	VAL_3	= 2,
	VAL_4	= 3,
	VAL_5	= 4,
	VAL_6	= 5,
	VAL_7	= 6,
	VAL_8	= 7,
	VAL_9	= 8,
	VAL_10 = 9,
	VAL_J	= 10,
	VAL_Q	= 11,
	VAL_K	= 12,
	VAL_A	= 13,
	VAL_SJ = 14,
	VAL_BJ = 15,
	VAL_MAX,
};
//扑克定义
enum emCard
{
	D_2  = MAKE_CARD(TYPE_DIAMOND,VAL_2),
	D_3  = MAKE_CARD(TYPE_DIAMOND,VAL_3),
	D_4  = MAKE_CARD(TYPE_DIAMOND,VAL_4),
	D_5  = MAKE_CARD(TYPE_DIAMOND,VAL_5),
	D_6  = MAKE_CARD(TYPE_DIAMOND,VAL_6),
	D_7  = MAKE_CARD(TYPE_DIAMOND,VAL_7),
	D_8  = MAKE_CARD(TYPE_DIAMOND,VAL_8),
	D_9  = MAKE_CARD(TYPE_DIAMOND,VAL_9),
	D_10 = MAKE_CARD(TYPE_DIAMOND,VAL_10),
	D_J  = MAKE_CARD(TYPE_DIAMOND,VAL_J),
	D_Q  = MAKE_CARD(TYPE_DIAMOND,VAL_Q),
	D_K  = MAKE_CARD(TYPE_DIAMOND,VAL_K),
	D_A  = MAKE_CARD(TYPE_DIAMOND,VAL_A),

	C_2  = MAKE_CARD(TYPE_CLUB,VAL_2),
	C_3  = MAKE_CARD(TYPE_CLUB,VAL_3),
	C_4  = MAKE_CARD(TYPE_CLUB,VAL_4),
	C_5  = MAKE_CARD(TYPE_CLUB,VAL_5),
	C_6  = MAKE_CARD(TYPE_CLUB,VAL_6),
	C_7  = MAKE_CARD(TYPE_CLUB,VAL_7),
	C_8  = MAKE_CARD(TYPE_CLUB,VAL_8),
	C_9  = MAKE_CARD(TYPE_CLUB,VAL_9),
	C_10 = MAKE_CARD(TYPE_CLUB,VAL_10),
	C_J  = MAKE_CARD(TYPE_CLUB,VAL_J),
	C_Q  = MAKE_CARD(TYPE_CLUB,VAL_Q),
	C_K  = MAKE_CARD(TYPE_CLUB,VAL_K),
	C_A  = MAKE_CARD(TYPE_CLUB,VAL_A),

	H_2  = MAKE_CARD(TYPE_HEART,VAL_2),
	H_3  = MAKE_CARD(TYPE_HEART,VAL_3),
	H_4  = MAKE_CARD(TYPE_HEART,VAL_4),
	H_5  = MAKE_CARD(TYPE_HEART,VAL_5),
	H_6  = MAKE_CARD(TYPE_HEART,VAL_6),
	H_7  = MAKE_CARD(TYPE_HEART,VAL_7),
	H_8  = MAKE_CARD(TYPE_HEART,VAL_8),
	H_9  = MAKE_CARD(TYPE_HEART,VAL_9),
	H_10 = MAKE_CARD(TYPE_HEART,VAL_10),
	H_J  = MAKE_CARD(TYPE_HEART,VAL_J),
	H_Q  = MAKE_CARD(TYPE_HEART,VAL_Q),
	H_K  = MAKE_CARD(TYPE_HEART,VAL_K),
	H_A  = MAKE_CARD(TYPE_HEART,VAL_A),

	S_2  = MAKE_CARD(TYPE_SPADE,VAL_2),
	S_3  = MAKE_CARD(TYPE_SPADE,VAL_3),
	S_4  = MAKE_CARD(TYPE_SPADE,VAL_4),
	S_5  = MAKE_CARD(TYPE_SPADE,VAL_5),
	S_6  = MAKE_CARD(TYPE_SPADE,VAL_6),
	S_7  = MAKE_CARD(TYPE_SPADE,VAL_7),
	S_8  = MAKE_CARD(TYPE_SPADE,VAL_8),
	S_9  = MAKE_CARD(TYPE_SPADE,VAL_9),
	S_10 = MAKE_CARD(TYPE_SPADE,VAL_10),
	S_J  = MAKE_CARD(TYPE_SPADE,VAL_J),
	S_Q  = MAKE_CARD(TYPE_SPADE,VAL_Q),
	S_K  = MAKE_CARD(TYPE_SPADE,VAL_K),
	S_A  = MAKE_CARD(TYPE_SPADE,VAL_A),

	SJ	 = MAKE_CARD(TYPE_JOKER,VAL_SJ),
	BJ   = MAKE_CARD(TYPE_JOKER,VAL_BJ),

	NIL  = CARD_NULL
};


enum eArrayType
{
	ARRAY_TYPE_ERROR			= -1,
	ARRAY_TYPE_SINGLE			= 1,
	ARRAY_TYPE_DOUBLE			= 2,
	ARRAY_TYPE_3				= 3,
	ARRAY_TYPE_BOMB				= 4,
	ARRAY_TYPE_SEQ				= 5,
	ARRAY_TYPE_SAMET            = 6,  //同花
	ARRAY_TYPE_3W2				= 7,	
	ARRAY_TYPE_4W1				= 8,  //4带1
	ARRAY_TYPE_SAMESEQ			= 9,  //同花顺
	ARRAY_TYPE_DOUBLE_DOUBLE	= 10,
	ARRAY_TYPE_SEQ2				= 13,
	ARRAY_TYPE_SEQ3				= 15,
	ARRAY_TYPE_PLANE			= 19,
	ARRAY_TYPE_510K_DIFF		= 38,
	ARRAY_TYPE_510K_COLOR		= 39,
	ARRAY_TYPE_JOKER_4			= 42,

};
#endif